### ISSUE TITLE
Bug when ralio start DEXXXXX

### ISSUE THREAD

**Issue by igorescobar** [oesmith/ralio#11]
Just reporting and documenting, there is a bug when you try to "start" on a "DE" on Rally, somehow Ralio try to find a TASK (TA) and assign me to the wrong task.

**Comment by oesmith** [comment]
Ralio's heavily set up for the setup my department uses - we only ever start and finish tasks, which probably explains why it errors when you try it with defects or user stories...

**Comment by igorescobar** [comment]
No problem! I will fix it on DE cases and in case of US's throw an friendly
error :)

**Comment by igorescobar** [comment]
Fixed in v0.2.0
