### ISSUE TITLE
Error occurs when tasks have a custom initial 'Scheduled State'

### ISSUE THREAD

**Issue by peteryates** [oesmith/ralio#21]
We have a custom scheduled state of `T` (Triage) before `D` (Defined).

With a bug in the `Triage` state, running the following causes this error:

```
»ralio sprint
  1 DE31 - · Some bug

TypeError: Cannot read property 'green' of undefined
    at CLI.printTaskLine (/usr/lib/node_modules/ralio/lib/cli.js:285:55)
    at /usr/lib/node_modules/ralio/lib/cli.js:70:16
    at Array.forEach (native)
    at /usr/lib/node_modules/ralio/lib/cli.js:59:13
    at /usr/lib/node_modules/ralio/lib/ralio.js:154:9
    at Request._callback (/usr/lib/node_modules/ralio/lib/ralio.js:62:7)
    at Request.self.callback (/usr/lib/node_modules/ralio/node_modules/request/main.js:120:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/usr/lib/node_modules/ralio/node_modules/request/main.js:555:16)
    at Request.EventEmitter.emit (events.js:95:17)
```

![rally_status_icons](https://f.cloud.github.com/assets/128088/452880/0a510d0a-b300-11e2-8b27-94864baef06b.png)

This is caused by the defect with the custom status; moving it on to `Defined` makes the command run successfully again.

**Comment by igorescobar** [comment]
Which version of ralio are you using?

**Comment by peteryates** [comment]
Sorry, that should have been in the initial report; I'm using `0.4.4`.

**Comment by igorescobar** [comment]
I've never heard about that status before. For us, before "Defined" is always "Grooming". I have to think about a solution for those who use non-official statuses.

**Comment by peteryates** [comment]
Ok, so it sounds from your setup you have 'Grooming' where we have 'Needs Triage'; this is the relevant part of our setup (in setup->workspace and projects->Fields->Scheduled State).

![scheduled_states](https://f.cloud.github.com/assets/128088/453454/32822a9a-b317-11e2-9640-46a1a6eb6a05.png)

**Comment by igorescobar** [comment]
I would tough in something more "graceful degradation" when ralio's dealing with a status code that he doesn't know. "Needs Triage" is a custom status it doesn't come with Rally's original setup, right?

**Comment by peteryates** [comment]
Yes, sorry, you're right.  It's a status that was originally called `Idea`, we renamed it to fit in with our internal process.

**Comment by igorescobar** [comment]
No problem, I will try to come up with a solution for those cases, Thank you!
