### ISSUE TITLE
Fix editor tests to be more portable

### ISSUE THREAD

**Issue by bdupras** [oesmith/ralio#34]
Travis CI tests are failing on the editor tests.  The tests assume /usr/bin/true and /usr/bin/false are available on the system to be exec'd, which is not portable.  Replace with purpose built node.js cli stubs?

**Comment by igorescobar** [comment]
I think that would be okay.

**Comment by bdupras** [comment]
Fixed by a7cc85ab528ac1480510856dab45e3c926e5b7c1.
