### ISSUE TITLE
SSO Login Support

### ISSUE THREAD

**Issue by timmyers** [oesmith/ralio#43]
Our company uses SSO login for Rally access.  Investigating what would be necessary to provide the capability to use ralio in this setting.

Any advice would be greatly appreciated.

**Comment by joshoohaah** [comment]
i was unable to get this working either.  I attempted to change line 12 in cli.js but that didn't work
`this.hostname = hostname || 'https://rally1.rallydev.com/';`

**Comment by timmyers** [comment]
It seems that the rally web API provides somewhat limited support for SSO authentication.  I have been able to get (with changes to another tool, pyral) read-only requests working, however it will not allow me to perform any modification requests.
