### ISSUE TITLE
More features for scrum masters?

### ISSUE THREAD

**Issue by igorescobar** [oesmith/ralio#5]
Hi @oesmith! 

Do do you think that is a good idea start developing new features for scrum masters?

The thing is that here is very common teams submit the tasks after the planning (2) to the scrum master and then he has to create all tasks inside of histories.

What kind of features do you think we can develop focusing on scrum masters?

I'm thinking in start to develop a feature that we can add tasks inside a history, in order of priority this is the top 1 for me.

What do you think?

**Comment by igorescobar** [comment]
On my recent pull request I've proposed a feature `ralio task create` and `ralio task delete` any toughts or changes?

**Comment by oesmith** [comment]
Adding/removing tasks is very useful. We tend to get the development team to add them directly though.

I've left comments on your pull request - thanks!

**Comment by igorescobar** [comment]
Yeah! Now developers can create those tasks directly from the command at the same time they discuss it :)

**Comment by igorescobar** [comment]
Hi @oesmith !

Recently, I had a conversation with a SM at Grupo Abril and he talked about a "feature". When they create a task to a story, they automatically add a "1 hour" effort to each story task because Rally automatically does a burn-down calculation. What do you think about that and do you think that should be integrated to Ralio as a default behavior or this should be passed a flag variable or something?

Thanks!
Igor.
