### ISSUE TITLE
Generating new Versions

### ISSUE THREAD

**Issue by igorescobar** [oesmith/ralio#9]
Hi @oesmith !

Are you using something to semantic versioning like https://github.com/kawamanza/step-up?

With this new feature I think that it's time to release the version 0.1.0. 
- Igor

**Comment by oesmith** [comment]
Step-up's probably a bit heavy for what we need right now. However, I totally encourage semver.org-style versioning :+1:

FWIW, you can install versions between releases by using:

```
npm install -g git+ssh://git@github.com/oesmith/ralio.git
```

**Comment by igorescobar** [comment]
I tried to publish a version v0.1.0 with npm publish and ..... :)

18:59:09 igorescobar@ubuntu ~/www/ralio  
npm publish
npm http PUT https://registry.npmjs.org/ralio
npm http 409 https://registry.npmjs.org/ralio
npm http GET https://registry.npmjs.org/ralio
npm http 200 https://registry.npmjs.org/ralio
npm http PUT https://registry.npmjs.org/ralio/0.1.0/-tag/latest
npm http 403 https://registry.npmjs.org/ralio/0.1.0/-tag/latest
npm ERR! publish Error sending version data
npm ERR! Error: forbidden user: igorescobar not authorized to modify ralio
npm ERR! Changed: dist-tags.latest "0.0.10" -> "0.1.0"

**Comment by oesmith** [comment]
You're on the list on npm now, too :godmode:

**Comment by igorescobar** [comment]
Thanks! ;)
